### ISSUE TITLE
ERROR: This script does not work on Python 3.6

### ISSUE THREAD

**Issue by dvishal485** [jayhale/vercel-django-example#5]
While deploying on vercel, the build fails with error message `ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.`

I am not really sure exactly how to implement the workaround by using `https://bootstrap.pypa.io/pip/3.6/get-pip.py`.

<details>
<summary>Vercel build logs</summary>

```
2022-02-12T08:42:23.682Z  
2022-02-12T08:42:23.692Z  Retrieving list of deployment files...
2022-02-12T08:42:25.202Z  Downloading 15 deployment files...
2022-02-12T08:42:25.645Z  Analyzing source code...
2022-02-12T08:42:25.710Z  Warning: Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings
2022-02-12T08:42:26.257Z  Installing build runtime...
2022-02-12T08:42:31.536Z  Build runtime installed: 5.279s
2022-02-12T08:42:32.259Z  Looking up build cache...
2022-02-12T08:42:32.798Z  Build Cache not found
2022-02-12T08:42:32.985Z  Starting build
2022-02-12T08:42:32.987Z        Build AMI version: Amazon Linux release 2 (Karoo)
2022-02-12T08:42:32.987Z        Lambda runtime: python3.6
2022-02-12T08:42:32.987Z        WSGI application: vercel_app.wsgi.application
2022-02-12T08:42:32.988Z  ====> Selecting python version
2022-02-12T08:42:32.996Z        Found matching python (python3.6)
2022-02-12T08:42:32.997Z  ====> Installing pip
2022-02-12T08:42:32.997Z  ----> Installing pip
2022-02-12T08:42:33.182Z        Running "python3.6 get-pip.py"
2022-02-12T08:42:33.243Z  ERROR Could not install pip
2022-02-12T08:42:33.245Z  Error: Command failed: python3.6 /tmp/59bdc86b/get-pip.py --user
2022-02-12T08:42:33.245Z
2022-02-12T08:42:33.246Z  ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
2022-02-12T08:42:33.246Z  
2022-02-12T08:42:33.246Z      at makeError (/vercel/7aa035dc158d0642/.build-utils/.builder/node_modules/execa/index.js:174:9)
2022-02-12T08:42:33.246Z      at /vercel/7aa035dc158d0642/.build-utils/.builder/node_modules/execa/index.js:278:16
2022-02-12T08:42:33.246Z      at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-02-12T08:42:33.246Z      at async Object.downloadAndInstallPip (/vercel/7aa035dc158d0642/.build-utils/.builder/node_modules/@ardnt/vercel-python-wsgi/build-utils/pip.js:35:17)
2022-02-12T08:42:33.247Z      at async Object.exports.build (/vercel/7aa035dc158d0642/.build-utils/.builder/node_modules/@ardnt/vercel-python-wsgi/index.js:39:19)
2022-02-12T08:42:33.247Z      at async Ttt (/var/task/sandbox.js:196:7754) {
2022-02-12T08:42:33.247Z    code: 1,
2022-02-12T08:42:33.248Z    stdout: 'ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.\n',
2022-02-12T08:42:33.248Z    stderr: '',
2022-02-12T08:42:33.248Z    failed: true,
2022-02-12T08:42:33.248Z    signal: null,
2022-02-12T08:42:33.248Z    cmd: 'python3.6 /tmp/59bdc86b/get-pip.py --user',
2022-02-12T08:42:33.248Z    timedOut: false,
2022-02-12T08:42:33.248Z    killed: false
2022-02-12T08:42:33.249Z  }
2022-02-12T08:42:34.037Z
```

</details>

**Comment by jayhale** [comment]
@dvishal485 a known issue - see here: https://github.com/ardnt/vercel-python-wsgi/issues/6

**Comment by dvishal485** [comment]
Oh didn't go through this one! Thanks :)

**Comment by LowScarlet** [comment]
how you fixed this

**Comment by jayhale** [comment]
@LowScarlet this was fixed with an update to the `vercel-python-wsgi` package.  As long as you're using latest there, this is no longer an issue.
